<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?>
</head>
<?php
genesis_markup( array(
  'html5'   => '<body %s>',
  'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
  'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
  'html5'   => '<div %s>',
  'xhtml'   => '<div id="wrap">',
  'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
  'html5'   => '<div %s>',
  'xhtml'   => '<div id="inner">',
  'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );

// Comes out of framework.php

do_action( 'genesis_before_content_sidebar_wrap' );
genesis_markup( array(
  'html5'   => '<div %s>',
  'xhtml'   => '<div id="content-sidebar-wrap">',
  'context' => 'content-sidebar-wrap',
) );

do_action( 'genesis_before_content' );
genesis_markup( array(
  'html5'   => '<main %s>',
  'xhtml'   => '<div id="content" class="hfeed">',
  'context' => 'content',
) );
do_action( 'genesis_before_loop' );
do_action( 'genesis_loop' );
do_action( 'genesis_after_loop' );
genesis_markup( array(
  'html5' => '</main>', //* end .content
  'xhtml' => '</div>', //* end #content
) );
do_action( 'genesis_after_content' );

echo '</div>'; //* end .content-sidebar-wrap or #content-sidebar-wrap
do_action( 'genesis_after_content_sidebar_wrap' );

/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>
</body>
</html>
